apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1 
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1
      #tolerations:
      #- effect: NoSchedule
      #  key: ignore-taint.cluster-autoscaler.kubernetes.io/mytaint
      #  operator: Equal
      #  value: init