apiVersion: v1
kind: Service
metadata:
  name: llama-2-70b
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 34.171.17.189
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: llama-2-70b
  sessionAffinity: None
  type: LoadBalancer