apiVersion: v1
kind: Service
metadata:
  name: svc-image-neg
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  selector:
    app: image
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080